#!/bin/bash

printf "Enter space separate list of job numbers: "
read job_numbers

printf "Enter new queue (e.g. HCPput, dque, etc.): "
read new_queue

echo "Moving job(s): ${job_numbers} to queue: ${new_queue}"
qalter ${job_numbers} -W queue=${new_queue}

