#!/bin/bash

printf "Enter name of file containing job numbers: "
read job_numbers_file_name

printf "Enter new queue (e.g. HCPput, dque, etc.): "
read new_queue

job_list_from_file=( $( cat ${job_numbers_file_name} ) )
job_list="`echo "${job_list_from_file[@]}"`"

for job in ${job_list} ; do
	if [[ ${job} != \#* ]]; then
		echo "Moving job: ${job} to queue ${new_queue}"
		qalter ${job} -W queue=${new_queue}
	fi
done


